baseURL: "https://eddy.lu"
languageCode: en-us
title: eddylu 
theme: PaperMod

params:
  homeInfoParams:
    Title: '🏄‍♂️探索 & 🧠重新思考'
    Content: '写一些给自己看的内容，然后觉得做一个网站比较屌而已'


outputs:
  home:
    - HTML
    - RSS
    - JSON 


menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 10

