baseURL: "https://eddy.lu"
languageCode: en-us
title: eddylu 点 eth 
theme: PaperMod

params:
  homeInfoParams:
    Title: '🏄‍♂️ 不入流的生活方式'
    Content: '记录一些探索，然后觉得做一个网站比较屌而已'


outputs:
  home:
    - HTML
    - RSS
    - JSON 


menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: now
      name: Now
      url: /now/
      weight: 30
    - identifier: 1
      name: 
      url: /1/
      weight: 50
    - identifier: 2
      name: 
      url: /2/
      weight: 50
    - identifier: 3
      name: 
      url: /3/
      weight: 50
    - identifier: 4
      name: 
      url: /4/
      weight: 50
      

